### ISSUE TITLE
update images and more discription

### ISSUE THREAD

**Issue by vkosuri** [VISHNU0906/DHT11_python_raspberry-pi#2]
@VISHNU0906 could you please update your project images?

**Comment by VISHNU0906** [comment]
![img-20190305-wa0018](https://user-images.githubusercontent.com/46535652/53825943-7d882300-3f9d-11e9-9102-dfcbbf2af2c3.jpg)

**Comment by vkosuri** [comment]
could you please add this image to readme.md?
